
import axios from "axios"

export default async (req, res) => {
  let {query, method} = req
  let corps = query.corps
  const url = `https://financialmodelingprep.com/api/v3/profile/${corps}?apikey=C0nnV4DbDeE3f8x224xsSgP6glPZz5tN`
  await axios
    .get(url)
    .then(({ data }) => {
      res.status(200).json({ data })
    })
    .catch(({ err }) => {
      res.status(400).json({ err })
    })
}

// https://financialmodelingprep.com/api/v3/profile/BYDIF?apikey=C0nnV4DbDeE3f8x224xsSgP6glPZz5tN
// [
//   {
//     "symbol": "WMT",
//     "price": 94.87,
//     "beta": 0.516,
//     "volAvg": 15380611,
//     "mktCap": 762127709300,
//     "lastDiv": 0.83,
//     "range": "51.20667-96.18",
//     "changes": 0.62,
//     "companyName": "Walmart Inc.",
//     "currency": "USD",
//     "cik": "0000104169",
//     "isin": "US9311421039",
//     "cusip": "931142103",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Discount Stores",
//     "website": "https://corporate.walmart.com",
//     "description": "Walmart Inc. engages in the operation of retail, wholesale, other units, and eCommerce worldwide. The company operates through three segments: Walmart U.S., Walmart International, and Sam's Club. It operates supercenters, supermarkets, hypermarkets, warehouse clubs, cash and carry stores, and discount stores under Walmart and Walmart Neighborhood Market brands; membership-only warehouse clubs; ecommerce websites, such as walmart.com.mx, walmart.ca, flipkart.com, PhonePe and other sites; and mobile commerce applications. The company offers grocery and consumables, including dairy, meat, bakery, deli, produce, dry, chilled or frozen packaged foods, alcoholic and nonalcoholic beverages, floral, snack foods, candy, other grocery items, health and beauty aids, paper goods, laundry and home care, baby care, pet supplies, and other consumable items; fuel, tobacco and other categories. It is also involved in the provision of health and wellness products covering pharmacy, optical and hearing services, and over-the-counter drugs and other medical products; and home and apparel including home improvement, outdoor living, gardening, furniture, apparel, jewelry, tools and power equipment, housewares, toys, seasonal items, mattresses and tire and battery centers. In addition, the company offers consumer electronics and accessories, software, video games, office supplies, appliances, and third-party gift cards. Further, it operates digital payment platforms; and offers financial services and related products, including money transfers, bill payments, money orders, check cashing, prepaid access, co-branded credit cards, installment lending, and earned wage access. Additionally, the company markets lines of merchandise under private brands, including Allswell, Athletic Works, Equate, and Free Assembly. The company was formerly known as Wal-Mart Stores, Inc. and changed its name to Walmart Inc. in February 2018. Walmart Inc. was founded in 1945 and is based in Bentonville, Arkansas.",
//     "ceo": "Mr. C. Douglas McMillon",
//     "sector": "Consumer Defensive",
//     "country": "US",
//     "fullTimeEmployees": "2100000",
//     "phone": "479 273 4000",
//     "address": "702 South West 8th Street",
//     "city": "Bentonville",
//     "state": "AR",
//     "zip": "72716",
//     "dcfDiff": 51.81023,
//     "dcf": 43.05976567889688,
//     "image": "https://images.financialmodelingprep.com/symbol/WMT.png",
//     "ipoDate": "1972-08-25",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "AMZN",
//     "price": 232.93,
//     "beta": 1.146,
//     "volAvg": 38889216,
//     "mktCap": 2449258950000,
//     "lastDiv": 0,
//     "range": "144.05-233.0",
//     "changes": 5.47,
//     "companyName": "Amazon.com, Inc.",
//     "currency": "USD",
//     "cik": "0001018724",
//     "isin": "US0231351067",
//     "cusip": "023135106",
//     "exchange": "NASDAQ Global Select",
//     "exchangeShortName": "NASDAQ",
//     "industry": "Specialty Retail",
//     "website": "https://www.amazon.com",
//     "description": "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions through online and physical stores in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). Its products offered through its stores include merchandise and content purchased for resale; and products offered by third-party sellers The company also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, Blink, eero, and Echo; and develops and produces media content. In addition, it offers programs that enable sellers to sell their products in its stores; and programs that allow authors, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, the company provides compute, storage, database, analytics, machine learning, and other services, as well as fulfillment, advertising, and digital content subscriptions. Additionally, it offers Amazon Prime, a membership program. The company serves consumers, sellers, developers, enterprises, content creators, and advertisers. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.",
//     "ceo": "Mr. Andrew R. Jassy",
//     "sector": "Consumer Cyclical",
//     "country": "US",
//     "fullTimeEmployees": "1551000",
//     "phone": "206 266 1000",
//     "address": "410 Terry Avenue North",
//     "city": "Seattle",
//     "state": "WA",
//     "zip": "98109-5210",
//     "dcfDiff": 182.1602,
//     "dcf": 50.76979954500106,
//     "image": "https://images.financialmodelingprep.com/symbol/AMZN.png",
//     "ipoDate": "1997-05-15",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "AAPL",
//     "price": 251.04,
//     "beta": 1.24,
//     "volAvg": 47321191,
//     "mktCap": 3794670432000,
//     "lastDiv": 0.99,
//     "range": "164.08-251.3789",
//     "changes": 2.91,
//     "companyName": "Apple Inc.",
//     "currency": "USD",
//     "cik": "0000320193",
//     "isin": "US0378331005",
//     "cusip": "037833100",
//     "exchange": "NASDAQ Global Select",
//     "exchangeShortName": "NASDAQ",
//     "industry": "Consumer Electronics",
//     "website": "https://www.apple.com",
//     "description": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.",
//     "ceo": "Mr. Timothy D. Cook",
//     "sector": "Technology",
//     "country": "US",
//     "fullTimeEmployees": "164000",
//     "phone": "408 996 1010",
//     "address": "One Apple Park Way",
//     "city": "Cupertino",
//     "state": "CA",
//     "zip": "95014",
//     "dcfDiff": 101.5266,
//     "dcf": 149.5133997524085,
//     "image": "https://images.financialmodelingprep.com/symbol/AAPL.png",
//     "ipoDate": "1980-12-12",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "UNH",
//     "price": 498.5,
//     "beta": 0.591,
//     "volAvg": 3859085,
//     "mktCap": 458761574000,
//     "lastDiv": 8.4,
//     "range": "436.38-630.73",
//     "changes": -21.98,
//     "companyName": "UnitedHealth Group Incorporated",
//     "currency": "USD",
//     "cik": "0000731766",
//     "isin": "US91324P1021",
//     "cusip": "91324P102",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Medical - Healthcare Plans",
//     "website": "https://www.unitedhealthgroup.com",
//     "description": "UnitedHealth Group Incorporated operates as a diversified health care company in the United States. It operates through four segments: UnitedHealthcare, Optum Health, Optum Insight, and Optum Rx. The UnitedHealthcare segment offers consumer-oriented health benefit plans and services for national employers, public sector employers, mid-sized employers, small businesses, and individuals; health care coverage and well-being services to individuals age 50 and older addressing their needs for preventive and acute health care services, as well as services dealing with chronic disease and other specialized issues for older individuals; Medicaid plans, children's health insurance and health care programs; health and dental benefits; and hospital and clinical services. The OptumHealth segment provides access to networks of care provider specialists, health management services, care delivery, consumer engagement, and financial services. This segment serves individuals directly through care delivery systems, employers, payers, and government entities. The OptumInsight segment offers software and information products, advisory consulting arrangements, and managed services outsourcing contracts to hospital systems, physicians, health plans, governments, life sciences companies, and other organizations. The OptumRx segment provides pharmacy care services and programs, including retail network contracting, home delivery, specialty and compounding pharmacy, and purchasing and clinical capabilities, as well as develops programs in the areas of step therapy, formulary management, drug adherence, and disease/drug therapy management. UnitedHealth Group Incorporated was incorporated in 1977 and is based in Minnetonka, Minnesota.",
//     "ceo": "Sir Andrew Philip Witty",
//     "sector": "Healthcare",
//     "country": "US",
//     "fullTimeEmployees": "440000",
//     "phone": "952 936 1300",
//     "address": "UnitedHealth Group Center",
//     "city": "Minnetonka",
//     "state": "MN",
//     "zip": "55343",
//     "dcfDiff": -369.8517,
//     "dcf": 868.3517049606377,
//     "image": "https://images.financialmodelingprep.com/symbol/UNH.png",
//     "ipoDate": "1984-10-17",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "XOM",
//     "price": 108.47,
//     "beta": 0.88,
//     "volAvg": 14787845,
//     "mktCap": 476735412300,
//     "lastDiv": 3.96,
//     "range": "95.77-126.34",
//     "changes": -2.37,
//     "companyName": "Exxon Mobil Corporation",
//     "currency": "USD",
//     "cik": "0000034088",
//     "isin": "US30231G1022",
//     "cusip": "30231G102",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Oil & Gas Integrated",
//     "website": "https://corporate.exxonmobil.com",
//     "description": "Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally. It operates through Upstream, Downstream, and Chemical segments. The company is also involved in the manufacture, trade, transport, and sale of crude oil, natural gas, petroleum products, petrochemicals, and other specialty products; manufactures and sells petrochemicals, including olefins, polyolefins, aromatics, and various other petrochemicals; and captures and stores carbon, hydrogen, and biofuels. As of December 31, 2021, it had approximately 20,528 net operated wells with proved reserves. The company was founded in 1870 and is headquartered in Irving, Texas.",
//     "ceo": "Mr. Darren W. Woods",
//     "sector": "Energy",
//     "country": "US",
//     "fullTimeEmployees": "62000",
//     "phone": "972-940-6000",
//     "address": "5959 Las Colinas Boulevard",
//     "city": "Irving",
//     "state": "TX",
//     "zip": "75039-2298",
//     "dcfDiff": -60.84848,
//     "dcf": 169.3184802108406,
//     "image": "https://images.financialmodelingprep.com/symbol/XOM.png",
//     "ipoDate": "1978-01-13",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "GOOGL",
//     "price": 196.66,
//     "beta": 1.034,
//     "volAvg": 26566804,
//     "mktCap": 2416259262996,
//     "lastDiv": 0.8,
//     "range": "130.67-199.0",
//     "changes": 6.84,
//     "companyName": "Alphabet Inc.",
//     "currency": "USD",
//     "cik": "0001652044",
//     "isin": "US02079K3059",
//     "cusip": "02079K305",
//     "exchange": "NASDAQ Global Select",
//     "exchangeShortName": "NASDAQ",
//     "industry": "Internet Content & Information",
//     "website": "https://www.abc.xyz",
//     "description": "Alphabet Inc. provides various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment offers products and services, including ads, Android, Chrome, hardware, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, and YouTube. It is also involved in the sale of apps and in-app purchases and digital content in the Google Play store; and Fitbit wearable devices, Google Nest home products, Pixel phones, and other devices, as well as in the provision of YouTube non-advertising services. The Google Cloud segment offers infrastructure, platform, and other services; Google Workspace that include cloud-based collaboration tools for enterprises, such as Gmail, Docs, Drive, Calendar, and Meet; and other services for enterprise customers. The Other Bets segment sells health technology and internet services. The company was founded in 1998 and is headquartered in Mountain View, California.",
//     "ceo": "Mr. Sundar  Pichai",
//     "sector": "Communication Services",
//     "country": "US",
//     "fullTimeEmployees": "181269",
//     "phone": "650 253 0000",
//     "address": "1600 Amphitheatre Parkway",
//     "city": "Mountain View",
//     "state": "CA",
//     "zip": "94043",
//     "dcfDiff": -3.64109,
//     "dcf": 200.3010852004325,
//     "image": "https://images.financialmodelingprep.com/symbol/GOOGL.png",
//     "ipoDate": "2004-08-19",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "MCK",
//     "price": 570.07,
//     "beta": 0.436,
//     "volAvg": 936775,
//     "mktCap": 72364685800,
//     "lastDiv": 2.84,
//     "range": "444.51-637.51",
//     "changes": -6.17,
//     "companyName": "McKesson Corporation",
//     "currency": "USD",
//     "cik": "0000927653",
//     "isin": "US58155Q1031",
//     "cusip": "58155Q103",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Medical - Distribution",
//     "website": "https://www.mckesson.com",
//     "description": "McKesson Corporation provides healthcare services in the United States and internationally. It operates through four segments: U.S. Pharmaceutical, International, Medical-Surgical Solutions, and Prescription Technology Solutions (RxTS). The U.S. Pharmaceutical segment distributes branded, generic, specialty, biosimilar, and over-the-counter pharmaceutical drugs and other healthcare-related products. This segment also provides practice management, technology, clinical support, and business solutions to community-based oncology and other specialty practices; and consulting, outsourcing, technological, and other services, as well as sells financial, operational, and clinical solutions to pharmacies. The International segment offers distribution and services to wholesale, institutional, and retail customers in 13 European countries and Canada. The Medical-Surgical Solutions segment provides medical-surgical supply distribution, logistics, and other services to healthcare providers. The RxTS segment serves biopharma and life sciences partners and patients to address medication challenges for patients throughout their journeys; connects pharmacies, providers, payers, and biopharma companies to deliver innovative access and adherence solutions; and provides third-party logistics and wholesale distribution support solutions. McKesson Corporation was founded in 1833 and is headquartered in Irving, Texas.",
//     "ceo": "Mr. Brian S. Tyler Ph.D.",
//     "sector": "Healthcare",
//     "country": "US",
//     "fullTimeEmployees": "45000",
//     "phone": "972 446 4800",
//     "address": "6555 State Highway 161",
//     "city": "Irving",
//     "state": "TX",
//     "zip": "75039",
//     "dcfDiff": -350.76221,
//     "dcf": 920.8322147758696,
//     "image": "https://images.financialmodelingprep.com/symbol/MCK.png",
//     "ipoDate": "1994-11-10",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "COR",
//     "price": 229.82,
//     "beta": 0.436,
//     "volAvg": 1432340,
//     "mktCap": 44419609600,
//     "lastDiv": 2.2,
//     "range": "199.75-253.27",
//     "changes": -2.42,
//     "companyName": "Cencora",
//     "currency": "USD",
//     "cik": "0001140859",
//     "isin": "US03073E1055",
//     "cusip": "03090BBJ8",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Medical - Distribution",
//     "website": "https://www.amerisourcebergen.com",
//     "description": "Cencora, Inc. sources and distributes pharmaceutical products. Its U.S. Healthcare Solutions segment distributes pharmaceuticals, over-the-counter healthcare products, home healthcare supplies and equipment, and related services to acute care hospitals and health systems, independent and chain retail pharmacies, mail order pharmacies, medical clinics, long-term care and alternate site pharmacies, and other customers. The company also provides pharmacy management, staffing, and other consulting services; supply management software to retail and institutional healthcare providers; packaging solutions to various institutional and retail healthcare providers; clinical trial support, product post-approval, and commercialization support services; data analytics, outcomes research, and additional services for biotechnology and pharmaceutical manufacturers; and pharmaceuticals, vaccines, parasiticides, diagnostics, micro feed ingredients, and other products to the companion animal and production animal markets. In addition, this segment distributes plasma and other blood products, injectable pharmaceuticals, vaccines, and other specialty products; and provides other services primarily to physicians who specialize in various disease states, primarily oncology, as well as to other healthcare providers, including hospitals and dialysis clinics. The company's International Healthcare Solutions segment offers international pharmaceutical wholesale and related service, and global commercialization services; and distributes pharmaceuticals, other healthcare products, and related services to pharmacies, doctors, health centers and hospitals primarily in Europe. This segment also provides specialty transportation and logistics services for the biopharmaceutical industry. The company was formerly known as AmerisourceBergen Corporation and changed its name to Cencora, Inc. in August 2023. Cencora, Inc. was incorporated in 2001 and is headquartered in Conshohocken, Pennsylvania.",
//     "ceo": "Dr. Robert P. Mauch Ph.D., PharmD",
//     "sector": "Healthcare",
//     "country": "US",
//     "fullTimeEmployees": "46000",
//     "phone": "610 727 7000",
//     "address": "1 West First Avenue",
//     "city": "Conshohocken",
//     "state": "PA",
//     "zip": "19428",
//     "dcfDiff": -487.32409,
//     "dcf": 731.684086853834,
//     "image": "https://images.financialmodelingprep.com/symbol/COR.png",
//     "ipoDate": "1995-04-04",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   },
//   {
//     "symbol": "CVS",
//     "price": 46.6,
//     "beta": 0.543,
//     "volAvg": 12508120,
//     "mktCap": 58641906000,
//     "lastDiv": 2.66,
//     "range": "46.38-83.25",
//     "changes": -2.77,
//     "companyName": "CVS Health Corporation",
//     "currency": "USD",
//     "cik": "0000064803",
//     "isin": "US1266501006",
//     "cusip": "126650100",
//     "exchange": "New York Stock Exchange",
//     "exchangeShortName": "NYSE",
//     "industry": "Medical - Healthcare Plans",
//     "website": "https://www.cvshealth.com",
//     "description": "CVS Health Corporation provides health services in the United States. The company's Health Care Benefits segment offers traditional, voluntary, and consumer-directed health insurance products and related services. It serves employer groups, individuals, college students, part-time and hourly workers, health plans, health care providers, governmental units, government-sponsored plans, labor groups, and expatriates. Its Pharmacy Services segment offers pharmacy benefit management solutions, including plan design and administration, formulary management, retail pharmacy network management, mail order pharmacy, specialty pharmacy and infusion, clinical, and disease and medical spend management services. It serves employers, insurance companies, unions, government employee groups, health plans, prescription drug plans, Medicaid managed care plans, plans offered on public health insurance and private health insurance exchanges, other sponsors of health benefit plans, and individuals. This segment operates retail specialty pharmacy stores; and specialty mail-order, mail-order dispensing, and compounding pharmacies, as well as branches for infusion and enteral nutrition services. The company's Retail/LTC segment sells prescription and over-the-counter drugs, consumer health and beauty products, and personal care products; and provides health care services through its MinuteClinic walk-in medical clinics. This segment also distributes prescription drugs; and provides related pharmacy consulting and other ancillary services to care facilities and other care settings. As of December 31, 2021, it operated approximately 9,900 retail locations and 1,200 MinuteClinic locations, as well as online retail pharmacy websites, LTC pharmacies, and onsite pharmacies. The company was formerly known as CVS Caremark Corporation and changed its name to CVS Health Corporation in September 2014. CVS Health Corporation was founded in 1963 and is headquartered in Woonsocket, Rhode Island.",
//     "ceo": "Mr. J. David Joyner CEBS",
//     "sector": "Healthcare",
//     "country": "US",
//     "fullTimeEmployees": "219000",
//     "phone": "401-765-1500",
//     "address": "One CVS Drive",
//     "city": "Woonsocket",
//     "state": "RI",
//     "zip": "02895",
//     "dcfDiff": -614.08836,
//     "dcf": 691.4082592109049,
//     "image": "https://images.financialmodelingprep.com/symbol/CVS.png",
//     "ipoDate": "1996-11-20",
//     "defaultImage": false,
//     "isEtf": false,
//     "isActivelyTrading": true,
//     "isAdr": false,
//     "isFund": false
//   }
// ]