  
module.exports = Object.assign(
    {},
    require('./auth.js'),
    require('./news.js'),
    require('./worldBank.js'),
    require('./ratings.js'),
    require('./historical.js'),
    require('./indicators.js'),
    require('./articles.js'),
    require('./calendar.js'),
    require('./calendarUpdates.js'),
    require('./comtrade.js'),
    require('./comtradeCountryByCategory.js'),
    require('./comtradeCountryFilterByType.js'),
    require('./comtradeTotalType.js'),
    require('./earnings.js'),
    require('./forecasts.js'),
    require('./federalReserve.js'),
    require('./wbHistorical.js'),
    require('./latestUpdates.js'),
    require('./marketSnap.js'),
    require('./marketIntraday.js'),
    require('./marketHistorical.js'),
    require('./marketForecasts.js'),
    require('./search.js'),
    require('./eurostat.js'),
    require('./eurostatHistorical.js'),
    require('./financials.js'),
    require('./financialsHistorical.js'),
    require('./getPeers.js'),
    require('./markertStockDescriptions.js'),
    require('./symbology.js')
);


